In [1]:
import warnings, pandas

warnings.filterwarnings("ignore")

In [2]:
names = ['UserID', 'MovieID', 'Rating', 'Timestamp']

rating = pandas.read_table("ratings.csv", sep=",", names=names, skiprows=1)

rating.iloc[:5]

   UserID  MovieID  Rating  Timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [3]:
rating.tail()

        UserID  MovieID  Rating   Timestamp
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

In [4]:
null = rating.isnull().sum()

null.sum()

np.int64(0)

In [5]:
total = rating.shape[0]

total

100836

In [6]:
total_film = rating["MovieID"].nunique()

total_film

9724

In [7]:
total_user = rating["UserID"].nunique()

total_user

610

In [8]:
rata_rata_rating = rating["Rating"].mean().round(3)

rata_rata_rating

np.float64(3.502)

In [9]:
rating_table = rating.pivot_table(index="MovieID", columns="UserID", values="Rating")

SparseRate = lambda table : round((table.isnull().sum().sum() / table.size) * 100, 3)

SparseRate(rating_table)

np.float64(98.3)

In [10]:
minimum_film_interaction = 10

WatchFilm = rating.groupby("MovieID")["Rating"].agg(["count", "mean"])

WatchFilm.columns = ["TotalWatch", "Rating"]

WatchFilm = WatchFilm[WatchFilm["TotalWatch"] > minimum_film_interaction]

rating = rating[rating["MovieID"].isin(WatchFilm.index)]

rating["MovieID"].nunique()

2121

In [11]:
rating_table = rating.pivot_table(index="MovieID", columns="UserID", values="Rating")

SparseRate(rating_table)

np.float64(93.845)

In [12]:
minimum_user_interaction = 50

UserWatch = rating.groupby("UserID")[["Rating"]].count()

UserWatch = UserWatch[UserWatch["Rating"] > minimum_user_interaction]

rating = rating[rating["UserID"].isin(UserWatch.index)]

In [13]:
rating_table = rating.pivot_table(index="MovieID", columns="UserID", values="Rating")

SparseRate(rating_table)

np.float64(90.396)

In [14]:
movies = pandas.read_table("movies.csv", sep=",", names=["MovieID", "Title", "Genre"], skiprows=1)

movies.iloc[:5]

,MovieID,Title,Genre
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [15]:
movies = movies.drop_duplicates("Title")

movies["Genre"] = movies["Genre"].apply(lambda i : " ".join(i.split("|")))

movies = movies[movies["Genre"] != "(no genres listed)"]

replacer = {"Sci-Fi":"SciFi", "Film-Noir":"Filnoir"}

for i, t in replacer.items():

  movies["Genre"] = movies["Genre"].str.replace(i, t)

movies.iloc[:5]

,MovieID,Title,Genre
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy
1,2,Jumanji (1995),Adventure Children Fantasy
2,3,Grumpier Old Men (1995),Comedy Romance
3,4,Waiting to Exhale (1995),Comedy Drama Romance
4,5,Father of the Bride Part II (1995),Comedy