In [1]:
import pandas

pandas.set_option('display.max_colwidth', None)

urls = "movies.csv"

data = pandas.read_table(urls, sep=',')

data.iloc[:5]

,MovieID,Title,Genre
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy
1,2,Jumanji (1995),Adventure Children Fantasy
2,3,Grumpier Old Men (1995),Comedy Romance
3,4,Waiting to Exhale (1995),Comedy Drama Romance
4,5,Father of the Bride Part II (1995),Comedy

In [2]:
data.tail()

,MovieID,Title,Genre
9698,193581,Black Butler: Book of the Atlantic (2017),Action Animation Comedy Fantasy
9699,193583,No Game No Life: Zero (2017),Animation Comedy Fantasy
9700,193585,Flint (2017),Drama
9701,193587,Bungo Stray Dogs: Dead Apple (2018),Action Animation
9702,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [3]:
data.isnull().sum().sum()

np.int64(0)

In [4]:
data.iloc[:, 1].nunique()

9703

In [5]:
rateUrl = "ratings.csv"

rating = pandas.read_table(rateUrl, sep=",", usecols=["UserID", "MovieID", "Rating"])

rating.columns = ["UserIds", "MovieIds", "Rating"]

rating.iloc[:5]

   UserIds  MovieIds  Rating
0        1         1     4.0
1        1         3     4.0
2        1         6     4.0
3        1        47     5.0
4        1        50     5.0

In [6]:
rating.tail()

        UserIds  MovieIds  Rating
100831      610    166534     4.0
100832      610    168248     5.0
100833      610    168250     5.0
100834      610    168252     5.0
100835      610    170875     3.0

In [7]:
rating.isnull().sum().sum()

np.int64(0)

In [8]:
totalUser = rating["UserIds"].nunique()

totalUser

610

In [9]:
totalTitle = rating["MovieIds"].nunique()

totalTitle

9724

In [10]:
rerata = float(rating.iloc[:, 2].mean().round(1))

rerata

3.5

In [11]:
resultTitle = rating.groupby("MovieIds").agg({"Rating": ["mean", "count"]})

resultTitle = resultTitle.reset_index()

resultTitle.columns = ["filmKey", "averageTitleRate", "totalTitleRate"]

resultTitle.iloc[:5]

   filmKey  averageTitleRate  totalTitleRate
0        1          3.920930             215
1        2          3.431818             110
2        3          3.259615              52
3        4          2.357143               7
4        5          3.071429              49

In [12]:
resultTitle.sort_values("averageTitleRate", ascending = False).iloc[:5]

      filmKey  averageTitleRate  totalTitleRate
9693   187717               5.0               1
4667     6983               5.0               1
3802     5328               5.0               1
7927    95843               5.0               1
2934     3941               5.0               1

In [13]:
meanRate = resultTitle['averageTitleRate'].mean()

threshold = resultTitle['totalTitleRate'].quantile(0.75)

def WeightRate(tabel, threshold, meanRate):

  totalRate = tabel['totalTitleRate']

  averageRate = tabel['averageTitleRate']

  return (totalRate / (totalRate + threshold) * averageRate) + (threshold / (totalRate + threshold) * meanRate)

In [14]:
resultTitle["WeightRate"] = WeightRate(resultTitle, threshold, meanRate)

resultTitle.sort_values("WeightRate", ascending = False).iloc[:5]

      filmKey  averageTitleRate  totalTitleRate  WeightRate
277       318          4.429022             317    4.396816
659       858          4.289062             192    4.243095
2224     2959          4.272936             218    4.232872
224       260          4.231076             251    4.197546
46         50          4.237745             204    4.196535

In [15]:
ratingTargetTabel = rating.pivot_table(index="MovieIds", columns="UserIds", values="Rating")

SparseRate = lambda table : float(round((table.isnull().sum().sum() / table.size) * 100, 3))

SparseRate(ratingTargetTabel)

98.3

In [16]:
ratingTargetTabel.iloc[:10, :10]

UserIds    1   2   3   4    5    6    7    8   9   10
MovieIds
1         4.0 NaN NaN NaN  4.0  NaN  4.5  NaN NaN NaN
2         NaN NaN NaN NaN  NaN  4.0  NaN  4.0 NaN NaN
3         4.0 NaN NaN NaN  NaN  5.0  NaN  NaN NaN NaN
4         NaN NaN NaN NaN  NaN  3.0  NaN  NaN NaN NaN
5         NaN NaN NaN NaN  NaN  5.0  NaN  NaN NaN NaN
6         4.0 NaN NaN NaN  NaN  4.0  NaN  NaN NaN NaN
7         NaN NaN NaN NaN  NaN  4.0  NaN  NaN NaN NaN
8         NaN NaN NaN NaN  NaN  3.0  NaN  NaN NaN NaN
9         NaN NaN NaN NaN  NaN  NaN  NaN  NaN NaN NaN
10        NaN NaN NaN NaN  NaN  3.0  NaN  2.0 NaN NaN